// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAW08b-cuISO8dpMTSpUqwxNyRaY0WvzE',
    appId: '1:399595255286:web:fb40c600924b35350b03d7',
    messagingSenderId: '399595255286',
    projectId: 'take45-5d697',
    authDomain: 'take45-5d697.firebaseapp.com',
    storageBucket: 'take45-5d697.firebasestorage.app',
    measurementId: 'G-9EJPWRRVXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8XGRCTRVBEndE8JJ3gGlmcltAaZ3jXVw',
    appId: '1:399595255286:android:ca28103da2cfc5fd0b03d7',
    messagingSenderId: '399595255286',
    projectId: 'take45-5d697',
    storageBucket: 'take45-5d697.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDNZDX4VeuYRfXnG2GPw9zBV57YrUEwWU',
    appId: '1:399595255286:ios:613818417c87c17d0b03d7',
    messagingSenderId: '399595255286',
    projectId: 'take45-5d697',
    storageBucket: 'take45-5d697.firebasestorage.app',
    iosBundleId: 'com.example.take45',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDNZDX4VeuYRfXnG2GPw9zBV57YrUEwWU',
    appId: '1:399595255286:ios:613818417c87c17d0b03d7',
    messagingSenderId: '399595255286',
    projectId: 'take45-5d697',
    storageBucket: 'take45-5d697.firebasestorage.app',
    iosBundleId: 'com.example.take45',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAW08b-cuISO8dpMTSpUqwxNyRaY0WvzE',
    appId: '1:399595255286:web:002c86de1f91d6650b03d7',
    messagingSenderId: '399595255286',
    projectId: 'take45-5d697',
    authDomain: 'take45-5d697.firebaseapp.com',
    storageBucket: 'take45-5d697.firebasestorage.app',
    measurementId: 'G-RX7W7JDGW8',
  );
}
